# Nginx
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Embedder-Policy "credentialless" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;

types {
  application/wasm wasm;
  text/javascript mjs js;
  application/octet-stream onnx ort gz;
}
